### ISSUE TITLE
打包发布到linux服务器报错，在mac下运行二进制包没有问题

### ISSUE THREAD

**Issue by ChinaArJun** [gogf/focus#4]
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
包发布到linux服务器报错

CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build main.go
在mac下运行二进制包没有问题

[root@vm172-31-16-137 focus]# ./main
2021-01-08 14:28:23.345 [FATA] SetServerRoot failed: cannot find file/folder "public" in following paths:
1. /home/docker/focus 
Stack:
1.  github.com/gogf/gf/net/ghttp.(*Server).SetServerRoot
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/net/ghttp/ghttp_server_config_static.go:56
2.  github.com/gogf/gf/net/ghttp.(*Server).SetConfig
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/net/ghttp/ghttp_server_config.go:306
3.  github.com/gogf/gf/net/ghttp.(*Server).SetConfigWithMap
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/net/ghttp/ghttp_server_config.go:298
4.  github.com/gogf/gf/frame/gins.Server.func1
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/frame/gins/gins_server.go:37
5.  github.com/gogf/gf/container/gmap.(*StrAnyMap).doSetWithLockCheck
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/container/gmap/gmap_hash_str_any_map.go:217
6.  github.com/gogf/gf/container/gmap.(*StrAnyMap).GetOrSetFuncLock
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/container/gmap/gmap_hash_str_any_map.go:254
7.  github.com/gogf/gf/frame/gins.Server
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/frame/gins/gins_server.go:23
8.  github.com/gogf/gf/frame/g.Server
    /Users/mac/go/pkg/mod/github.com/gogf/gf@v1.15.2-0.20210107113446-788ade2db012/frame/g/g_object.go:30
9.  focus/app.Run
    /Users/mac/go/src/focus/app/app.go:19
10. main.main
    /Users/mac/go/src/focus/main.go:12

**Comment by zcool321** [comment]
1、确认部署 public和template也copy了
2、官方推荐gf build打包

**Comment by ChinaArJun** [comment]
谢谢，确实linux打包没有加入静态文件，现在已经部署好了
